from typing import List, Dict, Any
from backend.indexer.schema import CodeChunk

class PRReporter:
    def generate_comment(
        self, 
        change_summary: str, 
        risk_tier: str, 
        dependents: List[CodeChunk], 
        reviewers: List[Dict[str, Any]]
    ) -> str:
        """
        Generates a markdown comment for GitHub/GitLab PRs.
        """
        header = f"### 🛡️ Dependency Impact Report: **{risk_tier}**\n\n"
        summary = f"**Change Summary**: {change_summary}\n\n"
        
        table_header = "| Impacted Symbol | Risk Score | Fan Out | Suggested Reviewer |\n"
        table_sep = "| :--- | :--- | :--- | :--- |\n"
        table_rows = ""
        
        for dep in dependents[:10]:
            # Simple heuristic for suggesting a reviewer from the provided list
            reviewer = reviewers[0]["name"] if reviewers else "N/A"
            table_rows += f"| `{dep.symbol_name}` | {round(dep.risk_score_current, 2)} | {dep.fan_out} | {reviewer} |\n"
            
        footer = "\n\n> [!TIP]\n> View the full interactive report in the [Impact Dashboard](#)."
        footer += "\n\n---\n*Report generated by Dependency Impact Analyzer v2.0*"
        
        return header + summary + table_header + table_sep + table_rows + footer

pr_reporter = PRReporter()
