from backend.query.response_validator import ValidatedResponse

class PRCommenter:
    TIER_EMOJIS = {
        "CRITICAL": "🚨",
        "HIGH": "⚠️",
        "MEDIUM": "🔍",
        "LOW": "✅",
        "UNKNOWN": "❓"
    }

    @staticmethod
    def render_markdown(response: ValidatedResponse) -> str:
        emoji = PRCommenter.TIER_EMOJIS.get(response.risk_tier, "ℹ️")
        
        md = f"## {emoji} Dependency Impact Analysis: **{response.risk_tier} RISK**\n\n"
        md += f"{response.summary}\n\n"
        
        if response.test_gap_suggestions and len(response.test_gap_suggestions) > 0:
            md += "### 🛡️ Test Coverage Gaps\n"
            md += "The following dependents lack sufficient test coverage for this change:\n\n"
            
            for gap in response.test_gap_suggestions:
                chunk_id = gap.get("chunk_id", "Unknown")
                suggestion = gap.get("suggestion", "")
                md += f"- **`{chunk_id}`**: {suggestion}\n"
                
        if response.hallucinations_stripped:
            md += "\n---\n*Note: Some AI suggestions were removed because they referenced invalid code chunks.*"
            
        md += "\n\n---\n*Generated by Dependency Impact Analyzer v2.0*"
        return md
